#!/bin/bash

# Alice
python sendA.py put 1024 1
python sendA.py put 1023 1
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py put 1023 1
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0
python sendA.py get 0

# Bob
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
python sendB.py get 0
